version: "3.0"
services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8123/ping || exit 1
      interval: 2s
      timeout: 2s
      retries: 16
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse/
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=12345
    networks:
      - my_network

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    ports:
      - "8080:80"
    depends_on:
      - clickhouse
    restart: unless-stopped
    environment:
      - CH_NAME=clickhouse
      - CH_HOST=http://localhost:8123
      - CH_LOGIN=default
      - CH_PASSWORD=12345

networks:
  my_network:
    driver: bridge
